# Generated by Django 4.1 on 2022-08-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyItem',
            new_name='Item',
        ),
    ]
